from __future__ import annotations

import json
import re
import time
from contextlib import nullcontext
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import Context
from playwright.async_api import async_playwright

from chatgpt_web_mcp.playwright.evidence import _capture_debug_artifacts, _ui_screenshot, _ui_snapshot_link, _ui_snapshot_run_dir
from chatgpt_web_mcp.providers.gemini.core import (
    _coerce_error_text,
    _ctx_info,
    _gemini_current_mode_text,
    _gemini_dismiss_overlays,
    _gemini_find_prompt_box,
    _gemini_focus_prompt_box,
    _gemini_open_tools_drawer,
    _gemini_tool_checked_from_attr,
    _human_pause,
    _is_tab_limit_error,
    _load_gemini_web_config,
    _open_gemini_page,
    _page_slot,
    _run_id,
    _tab_limit_result,
    _without_proxy_env,
)
from chatgpt_web_mcp.runtime.call_log import _maybe_append_call_log
from chatgpt_web_mcp.runtime.paths import _gemini_ui_snapshot_base_dir, _gemini_ui_snapshot_doc_path


_GEMINI_TOOL_TEXT_RE = re.compile(r"(Tools|工具)", re.I)


def _normalize_mode(raw_mode: str) -> str | None:
    normalized = re.sub(r"[^a-z]+", "", str(raw_mode or "").strip().lower())
    if normalized in {"basic", "full"}:
        return normalized
    return None


def _gemini_send_button_locator(page):
    return page.locator(
        "button[aria-label='发送'], "
        "button[aria-label='傳送'], "
        "button[aria-label='Send'], "
        "button.send-button"
    ).first


def _gemini_model_selector_locator(page):
    return page.locator(
        "button.current-mode-button, "
        "button[aria-label*='Model'], "
        "button[aria-label*='模型'], "
        "button[aria-label*='模式']"
    ).first


def _gemini_tools_button_locator(page):
    return page.locator(
        "button.toolbox-drawer-button, "
        "button[aria-label*='Tools'], "
        "button[aria-label*='工具']"
    ).first


def _collect_tools_checked_state(aria_checked: str | None, klass: str | None) -> bool | None:
    if isinstance(aria_checked, str):
        val = aria_checked.strip().lower()
        if val in {"true", "false"}:
            return val == "true"
    return _gemini_tool_checked_from_attr(aria_checked, klass)


def _looks_like_detached_dom_capture(result: dict[str, Any]) -> bool:
    error_type = str(result.get("error_type") or "").strip().lower()
    error_text = str(result.get("error") or "").strip().lower()
    if not error_type:
        return False
    return "attached" in error_text and "dom" in error_text


async def _capture_composer_prompt(page, *, prompt, run_dir: Path) -> dict[str, Any]:
    prompt = await _gemini_focus_prompt_box(page, prompt)
    await _human_pause(page)
    shot = await _ui_screenshot(page, target="composer_prompt", out_dir=run_dir, locator=prompt)
    if not _looks_like_detached_dom_capture(shot):
        return shot

    prompt = await _gemini_find_prompt_box(page, timeout_ms=3_000)
    prompt = await _gemini_focus_prompt_box(page, prompt)
    await _human_pause(page)
    retried = await _ui_screenshot(page, target="composer_prompt", out_dir=run_dir, locator=prompt)
    retried["retried_after_detached_dom"] = True
    return retried


async def _collect_visible_tools(page) -> list[dict[str, Any]]:
    tools: list[dict[str, Any]] = []
    items = page.locator(
        "div.cdk-overlay-pane:visible [role='menuitemcheckbox'], "
        "div.cdk-overlay-pane:visible button[role='menuitemcheckbox']"
    )
    try:
        n = int(await items.count())
    except Exception:
        n = 0
    for i in range(min(max(n, 0), 100)):
        it = items.nth(i)
        try:
            text = (await it.inner_text()) or ""
        except Exception:
            text = ""
        if not text.strip():
            continue
        try:
            aria = await it.get_attribute("aria-checked")
        except Exception:
            aria = None
        try:
            klass = await it.get_attribute("class")
        except Exception:
            klass = None
        tools.append(
            {
                "text": text.strip(),
                "checked": _collect_tools_checked_state(aria, klass),
            }
        )
    return tools


async def _gemini_ui_write_snapshot_doc(
    *,
    doc_path: Path,
    run_dir: Path,
    conversation_url: str,
    title: str,
    mode_text: str,
    targets: list[dict[str, Any]],
    tools: list[dict[str, Any]],
) -> None:
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# Gemini Web UI Reference (autogenerated)")
    lines.append("")
    lines.append(f"- Updated: `{time.strftime('%Y-%m-%d %H:%M:%S %z')}`")
    lines.append(f"- Conversation URL: `{conversation_url}`")
    if title.strip():
        lines.append(f"- Page title: `{title.strip()}`")
    if mode_text.strip():
        lines.append(f"- Current mode text: `{mode_text.strip()}`")
    lines.append(f"- Run dir: `{run_dir}`")
    lines.append("")
    lines.append("This doc points to local screenshots generated by `gemini_web_capture_ui`.")
    lines.append("")
    lines.append("## Snapshots")
    lines.append("")

    for item in targets:
        target = str(item.get("target") or "").strip()
        if not target:
            continue
        lines.append(f"### {target}")
        path_raw = item.get("path")
        if isinstance(path_raw, str) and path_raw.strip():
            link = _ui_snapshot_link(doc_path, Path(path_raw))
            lines.append(f"![](<{link}>)")
        else:
            err_type = str(item.get("error_type") or "").strip()
            err = str(item.get("error") or "").strip()
            if err_type or err:
                lines.append(f"- Error: `{(err_type + ': ' if err_type else '') + err}`")
        lines.append("")

    if tools:
        lines.append("## Tools Snapshot")
        lines.append("")
        for item in tools:
            text = str(item.get("text") or "").strip()
            checked = item.get("checked")
            marker = "?" if checked is None else ("on" if bool(checked) else "off")
            lines.append(f"- [{marker}] {text}")
        lines.append("")

    doc_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


async def gemini_web_capture_ui(
    conversation_url: str | None = None,
    mode: str = "basic",
    timeout_seconds: int = 90,
    out_dir: str | None = None,
    write_doc: bool = True,
    ctx: Context | None = None,
) -> dict[str, Any]:
    cfg = _load_gemini_web_config()
    started_at = time.time()
    run_id = _run_id(tool="gemini_web_capture_ui")

    normalized_mode = _normalize_mode(mode)
    if normalized_mode is None:
        return {
            "ok": False,
            "status": "error",
            "error_type": "ValueError",
            "error": f"Unsupported mode: {mode} (use 'basic' or 'full')",
            "elapsed_seconds": round(time.time() - started_at, 3),
            "run_id": run_id,
        }

    run_dir = Path(out_dir).expanduser() if (out_dir or "").strip() else _ui_snapshot_run_dir(_gemini_ui_snapshot_base_dir())
    doc_path = _gemini_ui_snapshot_doc_path()
    env_ctx = _without_proxy_env() if cfg.cdp_url else nullcontext()
    with env_ctx:
        async with _page_slot(kind="gemini", ctx=ctx), async_playwright() as p:
            browser = None
            context = None
            page = None
            close_context = False
            targets: list[dict[str, Any]] = []
            tools: list[dict[str, Any]] = []
            notes: list[str] = []
            title = ""
            mode_text = ""
            conversation_url_effective = ""
            try:
                browser, context, page, close_context = await _open_gemini_page(
                    p,
                    cfg,
                    conversation_url=conversation_url,
                    ctx=ctx,
                )
                conversation_url_effective = (page.url or "").strip()
                prompt = await _gemini_find_prompt_box(page, timeout_ms=max(5_000, int(timeout_seconds * 1000)))
                await _human_pause(page)

                try:
                    title = (await page.title()).strip()
                except Exception:
                    title = ""
                try:
                    mode_text = await _gemini_current_mode_text(page)
                except Exception:
                    mode_text = ""

                targets.append(await _ui_screenshot(page, target="page_full", out_dir=run_dir, full_page=True))
                targets.append(await _capture_composer_prompt(page, prompt=prompt, run_dir=run_dir))
                targets.append(
                    await _ui_screenshot(
                        page,
                        target="send_button",
                        out_dir=run_dir,
                        locator=_gemini_send_button_locator(page),
                    )
                )
                targets.append(
                    await _ui_screenshot(
                        page,
                        target="model_selector_button",
                        out_dir=run_dir,
                        locator=_gemini_model_selector_locator(page),
                    )
                )
                targets.append(
                    await _ui_screenshot(
                        page,
                        target="tools_button",
                        out_dir=run_dir,
                        locator=_gemini_tools_button_locator(page),
                    )
                )

                if normalized_mode == "full":
                    try:
                        await _gemini_open_tools_drawer(page)
                        await _human_pause(page)
                        tools = await _collect_visible_tools(page)
                        overlay = page.locator("div.cdk-overlay-pane:visible").first
                        targets.append(
                            await _ui_screenshot(
                                page,
                                target="tools_overlay",
                                out_dir=run_dir,
                                locator=overlay,
                            )
                        )
                    except Exception as exc:
                        notes.append(f"tools_overlay_unavailable={type(exc).__name__}:{exc}")
                        targets.append({"target": "tools_overlay", "error_type": type(exc).__name__, "error": str(exc)})
                    finally:
                        try:
                            await _gemini_dismiss_overlays(page)
                        except Exception:
                            pass

                    latest_answer = page.locator("model-response").last
                    targets.append(
                        await _ui_screenshot(
                            page,
                            target="latest_answer_block",
                            out_dir=run_dir,
                            locator=latest_answer,
                        )
                    )

                if not tools:
                    notes.append("no_tools_detected")
                if not any(_GEMINI_TOOL_TEXT_RE.search(str(t.get("text") or "")) for t in tools):
                    notes.append("tools_menu_text_not_detected")

                run_dir.mkdir(parents=True, exist_ok=True)
                manifest_path = run_dir / "manifest.json"
                payload = {
                    "tool": "gemini_web_capture_ui",
                    "run_id": run_id,
                    "captured_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
                    "conversation_url": conversation_url_effective,
                    "title": title,
                    "mode_text": mode_text,
                    "mode": normalized_mode,
                    "targets": targets,
                    "tools": tools,
                    "notes": notes,
                }
                manifest_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

                if write_doc:
                    await _gemini_ui_write_snapshot_doc(
                        doc_path=doc_path,
                        run_dir=run_dir,
                        conversation_url=conversation_url_effective,
                        title=title,
                        mode_text=mode_text,
                        targets=targets,
                        tools=tools,
                    )

                result = {
                    "ok": True,
                    "status": "completed",
                    "conversation_url": conversation_url_effective,
                    "run_id": run_id,
                    "mode": normalized_mode,
                    "out_dir": str(run_dir),
                    "manifest_path": str(manifest_path),
                    "doc_path": (str(doc_path) if write_doc else None),
                    "targets": targets,
                    "tools": tools,
                    "title": title,
                    "mode_text": mode_text,
                    "notes": notes,
                    "elapsed_seconds": round(time.time() - started_at, 3),
                }
                _maybe_append_call_log(
                    {
                        "tool": "gemini_web_capture_ui",
                        "ok": True,
                        "status": "completed",
                        "run_id": run_id,
                        "elapsed_seconds": result.get("elapsed_seconds"),
                        "conversation_url": conversation_url_effective,
                        "params": {
                            "conversation_url": conversation_url,
                            "mode": normalized_mode,
                            "timeout_seconds": timeout_seconds,
                            "out_dir": (str(out_dir) if out_dir else None),
                            "write_doc": bool(write_doc),
                        },
                        "manifest_path": str(manifest_path),
                        "doc_path": (str(doc_path) if write_doc else None),
                    }
                )
                return result
            except Exception as exc:
                if _is_tab_limit_error(exc):
                    result = _tab_limit_result(
                        tool="gemini_web_capture_ui",
                        run_id=run_id,
                        started_at=started_at,
                        conversation_url=(conversation_url_effective or conversation_url),
                    )
                    _maybe_append_call_log(
                        {
                            "tool": "gemini_web_capture_ui",
                            "ok": False,
                            "status": result.get("status"),
                            "run_id": run_id,
                            "elapsed_seconds": result.get("elapsed_seconds"),
                            "conversation_url": result.get("conversation_url"),
                            "error_type": result.get("error_type"),
                            "error": result.get("error"),
                        }
                    )
                    return result

                artifacts: dict[str, str] = {}
                if page is not None:
                    artifacts = await _capture_debug_artifacts(page, label="gemini_capture_ui_error")
                    if ctx and artifacts:
                        await _ctx_info(ctx, f"Saved debug artifacts: {artifacts}")

                result = {
                    "ok": False,
                    "status": "error",
                    "error_type": type(exc).__name__,
                    "error": _coerce_error_text(exc),
                    "run_id": run_id,
                    "elapsed_seconds": round(time.time() - started_at, 3),
                    "conversation_url": conversation_url_effective or conversation_url,
                    "debug_artifacts": artifacts,
                    "targets": targets,
                    "tools": tools,
                    "notes": notes,
                }
                _maybe_append_call_log(
                    {
                        "tool": "gemini_web_capture_ui",
                        "ok": False,
                        "status": "error",
                        "run_id": run_id,
                        "elapsed_seconds": result.get("elapsed_seconds"),
                        "conversation_url": result.get("conversation_url"),
                        "error_type": type(exc).__name__,
                        "error": str(exc),
                        "debug_artifacts": artifacts,
                    }
                )
                return result
            finally:
                try:
                    if page is not None:
                        try:
                            await page.close()
                        except Exception:
                            pass
                    if close_context and context is not None:
                        await context.close()
                finally:
                    if browser is not None:
                        await browser.close()
