#!/usr/bin/env bash
# Internal driver MCP entry.
# Used by worker / repair / maintenance flows; not the default northbound surface for coding agents.
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

export FASTMCP_HOST="${FASTMCP_HOST:-127.0.0.1}"
export FASTMCP_PORT="${FASTMCP_PORT:-18701}"

if [[ -z "${CHATGPT_CDP_URL:-}" ]]; then
  CHROME_DEBUG_PORT="${CHROME_DEBUG_PORT:-9222}"
  export CHATGPT_CDP_URL="http://127.0.0.1:${CHROME_DEBUG_PORT}"
fi

export GEMINI_CDP_URL="${GEMINI_CDP_URL:-${CHATGPT_CDP_URL}}"
export QWEN_CDP_URL="${QWEN_CDP_URL:-http://127.0.0.1:9335}"
export CHATGPT_CDP_AUTO_START="${CHATGPT_CDP_AUTO_START:-1}"
export GEMINI_CDP_AUTO_START="${GEMINI_CDP_AUTO_START:-${CHATGPT_CDP_AUTO_START}}"
export QWEN_CDP_AUTO_START="${QWEN_CDP_AUTO_START:-0}"
export CHATGPT_CDP_AUTO_RESTART="${CHATGPT_CDP_AUTO_RESTART:-1}"
export GEMINI_CDP_AUTO_RESTART="${GEMINI_CDP_AUTO_RESTART:-${CHATGPT_CDP_AUTO_RESTART}}"
export QWEN_CDP_AUTO_RESTART="${QWEN_CDP_AUTO_RESTART:-0}"
export CHATGPT_CDP_FALLBACK_STORAGE_STATE="${CHATGPT_CDP_FALLBACK_STORAGE_STATE:-0}"
export GEMINI_CDP_FALLBACK_STORAGE_STATE="${GEMINI_CDP_FALLBACK_STORAGE_STATE:-0}"
export QWEN_CDP_FALLBACK_STORAGE_STATE="${QWEN_CDP_FALLBACK_STORAGE_STATE:-0}"
export CHATGPT_MIN_PROMPT_INTERVAL_SECONDS="${CHATGPT_MIN_PROMPT_INTERVAL_SECONDS:-61}"
export GEMINI_MIN_PROMPT_INTERVAL_SECONDS="${GEMINI_MIN_PROMPT_INTERVAL_SECONDS:-61}"
export QWEN_MIN_PROMPT_INTERVAL_SECONDS="${QWEN_MIN_PROMPT_INTERVAL_SECONDS:-0}"
export CHATGPT_ACTION_DELAY_MS="${CHATGPT_ACTION_DELAY_MS:-600,1200}"
export CHATGPT_PRO_DEFAULT_THINKING_TIME="${CHATGPT_PRO_DEFAULT_THINKING_TIME:-extended}"
# Fail-closed: require UI confirmation that each uploaded attachment is present.
export CHATGPT_UPLOAD_REQUIRE_CONFIRM="${CHATGPT_UPLOAD_REQUIRE_CONFIRM:-1}"
# Optional: browser network "packet capture" style logs (Playwright request/response metadata; no headers/body).
export CHATGPT_NETLOG_ENABLED="${CHATGPT_NETLOG_ENABLED:-0}"
export CHATGPT_NETLOG_MAX_BYTES="${CHATGPT_NETLOG_MAX_BYTES:-10000000}"
export CHATGPT_NETLOG_BACKUP_COUNT="${CHATGPT_NETLOG_BACKUP_COUNT:-3}"
export CHATGPT_NETLOG_RESOURCE_TYPES="${CHATGPT_NETLOG_RESOURCE_TYPES:-xhr,fetch,eventsource,websocket}"
export CHATGPT_NETLOG_HOST_ALLOWLIST="${CHATGPT_NETLOG_HOST_ALLOWLIST:-chatgpt.com,ab.chatgpt.com}"
export CHATGPT_NETLOG_REDACT_QUERY="${CHATGPT_NETLOG_REDACT_QUERY:-1}"
export CHATGPT_NETLOG_REDACT_IDS="${CHATGPT_NETLOG_REDACT_IDS:-1}"
export CHATGPT_NETLOG_LINE_MAX_CHARS="${CHATGPT_NETLOG_LINE_MAX_CHARS:-2000}"
# Optional: log a small whitelist of routing fields from POST /backend-api/conversation (NO prompt content).
export CHATGPT_NETLOG_CAPTURE_MODEL_ROUTE="${CHATGPT_NETLOG_CAPTURE_MODEL_ROUTE:-0}"
export MCP_DEBUG_DIR="${MCP_DEBUG_DIR:-artifacts}"
export MCP_CALL_LOG="${MCP_CALL_LOG:-artifacts/mcp_calls.jsonl}"
# Persist driver state across restarts (avoid duplicate sends / blocked-state loss).
DRIVER_STATE_DIR="${CHATGPTREST_DRIVER_STATE_DIR:-${ROOT_DIR}/state/driver}"
mkdir -p "${DRIVER_STATE_DIR}"
chmod 700 "${DRIVER_STATE_DIR}" 2>/dev/null || true
export MCP_SERVER_LOCK_FILE="${MCP_SERVER_LOCK_FILE:-${DRIVER_STATE_DIR}/chatgpt_web_mcp_server.lock}"
export MCP_IDEMPOTENCY_DB="${MCP_IDEMPOTENCY_DB:-${DRIVER_STATE_DIR}/mcp_idempotency.sqlite3}"
export CHATGPT_BLOCKED_STATE_FILE="${CHATGPT_BLOCKED_STATE_FILE:-${DRIVER_STATE_DIR}/chatgpt_blocked_state.json}"
export CHATGPT_GLOBAL_RATE_LIMIT_FILE="${CHATGPT_GLOBAL_RATE_LIMIT_FILE:-${DRIVER_STATE_DIR}/chatgpt_rate_limit.json}"
# Prevent refresh storms across repeated wait polls (best-effort, persisted state).
export CHATGPT_WAIT_REFRESH_STATE_FILE="${CHATGPT_WAIT_REFRESH_STATE_FILE:-${DRIVER_STATE_DIR}/chatgpt_wait_refresh_state.json}"
export CHATGPT_WAIT_REFRESH_MIN_INTERVAL_SECONDS="${CHATGPT_WAIT_REFRESH_MIN_INTERVAL_SECONDS:-900}"
export CHATGPT_WAIT_REFRESH_WINDOW_SECONDS="${CHATGPT_WAIT_REFRESH_WINDOW_SECONDS:-86400}"
export CHATGPT_WAIT_REFRESH_MAX_PER_WINDOW="${CHATGPT_WAIT_REFRESH_MAX_PER_WINDOW:-12}"
# Pro thinking quality guard: treat "Thought for < N seconds" as abnormal (default 5min).
export CHATGPT_THOUGHT_GUARD_MIN_SECONDS="${CHATGPT_THOUGHT_GUARD_MIN_SECONDS:-300}"
# Regenerate guard (no new user prompt; still side-effectful UI action).
export CHATGPT_REGENERATE_STATE_FILE="${CHATGPT_REGENERATE_STATE_FILE:-${DRIVER_STATE_DIR}/chatgpt_regenerate_state.json}"
export CHATGPT_REGENERATE_MIN_INTERVAL_SECONDS="${CHATGPT_REGENERATE_MIN_INTERVAL_SECONDS:-1800}"
export CHATGPT_REGENERATE_WINDOW_SECONDS="${CHATGPT_REGENERATE_WINDOW_SECONDS:-86400}"
export CHATGPT_REGENERATE_MAX_PER_WINDOW="${CHATGPT_REGENERATE_MAX_PER_WINDOW:-3}"
# Ensure auto-started Chrome inherits proxy settings (used by ops/chrome_start.sh).
export CHROME_PROXY_SERVER="${CHROME_PROXY_SERVER:-${CHATGPT_PROXY_SERVER:-${ALL_PROXY:-}}}"

exec "${ROOT_DIR}/.venv/bin/python" "${ROOT_DIR}/chatgptrest_driver_server.py" --transport streamable-http
